trainingInput:
  runtimeVersion: '1.13'
  pythonVersion: '3.5'
  scaleTier: CUSTOM
  masterType: standard
  workerType: standard
  parameterServerType: standard
  workerCount: 3
  parameterServerCount: 1
